config/routes.rb
AnandSampat::Application.routes.draw do
  get "contact_form/new"

  get "contact_form/create"

  get "users/new"

  root to:'static_pages#home'

  match '/signup',  to: 'users#new'

  
  match '/about',   to: 'static_pages#about'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  

  match '/projects', to: 'static_pages#projects'

  match '/blog', to:'static_pages#blog'

  match '/reading', to:'static_pages#reading'

  match '/book_reading', to: 'static_pages#book_reading'

  match '/resume' => redirect('https://docs.google.com/file/d/0B_j1yTxBbZYAS3FubHpCamJmN1U/edit'), :as => :resume

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :categories
  attr_accessible :author, :content, :summary, :title, :url, :timestamps
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :average_rating, :description, :image_url, :isbn, :link, :num_pages, :publication_day, :publication_month, :publication_year, :title,:authors,:shelves
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
  attr_accessible :name
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name

  # allow user to be the user of the blog

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i 
  validates :email, presence: true, format: {with:VALID_EMAIL_REGEX}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def help
  end
  
  def about
  end

  def reading
    @articles = Article.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def book_reading
    @books_read = Book.order("publication_year DESC").paginate(:page => params[:page], :per_page => 5)
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Setup the meta tags for better SEO on website
  def setup_meta_tags_params()
    set_meta_tags :title=> 'Anand Sampat',
                  :description => "Hi! I'm Anand and I dream about efficiency. Building and creating is just as important to me as learning. My ultimate dream is to create the perfect music creation app.",
                  :keywords => %w[ruby rails anand sampat engineer software hardware berkeley stanford ],
                  :canonical => "http://www.anandsampat.com",
                  :og => {
                    :title    => 'Anand Sampat',
                    :type     => 'article',
                    :url      => 'http://www.anandsampat.com',
                    :image    => 'http://oi44.tinypic.com/w2cbiq.jpg',
                    :description => "Hi! I'm Anand and I dream about efficiency. Building and creating is just as important to me as learning. My ultimate dream is to create the perfect music creation app.",
                    :site_name => 'Anand Sampat'
                    #:video    => {
                    #  :director => 'http://www.imdb.com/name/nm0000881/',
                    #  :writer   => ['http://www.imdb.com/name/nm0918711/', 'http://www.imdb.com/name/nm0177018/']
                    #}
                  }
  end
  
  # Setup open graph tags for website
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Anand Sampat"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  # blog page helper functions
  def load_blog_feed
    feed = feedjira::Feed.fetch_and_parse("http://anandsampat.wordpress.com/feed");
    unless feed.is_a?(Fixnum)
      @feed_title = feed.title;
      @blog_posts = feed.entries[0...3]; nil
    else
      @blog_posts = []
    end
  end
  
  # reading page helper functions
  def load_reading_feed
    # add this to database if it doesn't exist in the database already 
    feedjira::Feed.fetch_and_parse("http://getpocket.com/users/anand.sampat/feed/read").entries.each do |e|
      # only add an item if the unique title is not already in the databse (assuming no article has the same title-I hope :-)
      if !Article.exists?(url: e.url)
        temp2=Article.create(url: e.url)
        temp2.created_at = e.published
        temp2.save
        # add in the categories
        for cat in e.categories
          temp2.categories.create(name: cat)
        end
      end
    end
  end

  # book reading page helper function
  def load_book_feed
    # Use the Goodreads API to access my personal public profile
    # key: xIgnxTVcHqymrVEy1Nmcg
    # secret: 8N6IxNhOFAyPJHEQkc7QJIMj9qCIo1DVIxknWFIE
    require 'open-uri'
    # Get all of the read books from Goodreads
    xml_feed = Nokogiri::XML(open("https://www.goodreads.com/review/list?format=xml&v=2&key=xIgnxTVcHqymrVEy1Nmcg&id=25848331&shelf=read", "User-Agent" => "ruby"))
    book_reviews = xml_feed.xpath("//reviews/review")
    # Loop through each of the book reviews 
    book_reviews.each do |review|
      isbn = review.xpath("book/isbn").text.to_i
      title = review.xpath("book/title").text
      image_url = review.xpath("book/image_url").text
      link = review.xpath("book/link").text
      num_pages = review.xpath("book/num_pages").text.to_i
      publication_day = review.xpath("book/publication_day").text.to_i
      publication_year = review.xpath("book/publication_year").text.to_i
      publication_month = review.xpath("book/publication_month").text.to_i
      average_rating = review.xpath("book/average_rating").text.to_f
      description = review.xpath("book/description").text
      description = Nokogiri::HTML(description).text
      authors = [review.xpath("book/authors").children.map{|author_arr| author_arr.children.map{|attr| attr.text}}[3]]
      shelves = ["read"]
      # Add this book to the database
      if !Book.exists?(isbn: isbn)
        Book.create(isbn:isbn,title:title,image_url:image_url,link:link,num_pages:num_pages,publication_day:publication_day,publication_year:publication_year,publication_month:publication_month,average_rating:average_rating,description:description,authors:authors,shelves:shelves)
      end      
    end  
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/new.html.erb
<% provide(:title, 'Contact Me') %>
<h1>Contact</h1>

<%= form_for @message, :url => contact_path, :html => {:class => "form-horizontal"} do |form| %>
    <fieldset>
      <div class="control-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'span12' %>
      </div>

      <div class="control-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'span12' %>
      </div>
      <div class="control-group">
        <%= form.label :subject %>
        <%= form.text_field :subject, class: 'span12' %>
      </div>

      <div class="control-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'span12' %>
      </div>
    </fieldset>

    <fieldset class="actions">
      <%= form.submit "Send", class: 'span12' %>
    </fieldset>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright 2013 Anand Sampat
  </small>
  <nav>
    <ul>
      <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
      <li class="<%= 'active' if current_page?(projects_path) %>"><%= link_to "Projects", projects_path %></li>
      <li class="<%= 'active' if current_page?(resume_path) %>"><%= link_to "Resume", resume_path %></li>
      <li class="<%= 'active' if current_page?(book_reading_path) %>"><%=  link_to "Books I'm Reading", book_reading_path %></li>
      <li class="<%= 'active' if current_page?(reading_path) %>"><%=  link_to "Articles I'm Reading", reading_path %></li>
      <!--<li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact Me", contact_path %></li>-->
      <li class="<%= 'active' if current_page?(blog_path) %>"><%= link_to "Blog", blog_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar">
    <div class="navbar-inner">

      <%= link_to image_tag("homepage/anand_logo.png", alt: "personal logo", size: "125x45"), '#', id: "logo" %>
      <ul class="nav pull-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
        <li class="<%= 'active' if current_page?(projects_path) %>"><%= link_to "Projects", projects_path %></li>
        <li class="<%= 'active' if current_page?(resume_path) %>"><%= link_to "Resume", resume_path %></li>
        <li class="<%= 'active' if current_page?(book_reading_path) %>"><%=  link_to "Books I'm Reading", book_reading_path %></li>
        <li class="<%= 'active' if current_page?(reading_path) %>"><%=  link_to "Articles I'm Reading", reading_path %></li>
        <!--<li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact Me", contact_path %></li> -->
        <li class="<%= 'active' if current_page?(blog_path) %>"><%= link_to "Blog", blog_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= analytics_init if Rails.env.production? %>
    <meta charset="utf-8">
    <% setup_meta_tags_params %>
    <%= display_meta_tags %>
    <%= javascript_include_tag 'jquery.inview.min' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
	  <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/_article.html.erb
<% require 'embedly' %>
<% @articles.each do |article| %>
    <ul class="thumbnails">
      <li class="span12">
        <% embedly_api = Embedly::API.new :key => '8a3c9238c6504b64816fcfc54fc2fa89', :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; asampat3090@gmail.com)' %>
        <%   obj = embedly_api.oembed(url: article.url, maxwidth: 450, wmode: 'transparent', method: 'after')  %>

        <a href=<%=article.url%> class="thumbnail" target="_blank">
            <br/>
            <h2><%= obj[0].title%></h2>
            <br/>
            <h4 class="text-center"> <%= image_tag obj[0].provider_url + "/favicon.ico", alt: "provider favicon", size: "64x64" %></h4>
            <br/>
            <% if obj[0].thumbnail_url != nil %>
            <%= image_tag obj[0].thumbnail_url, alt: obj[0].title %>
            <% end %>
            <br/>
            <p><%= obj[0].description %> </p>
        </a>
      </li>
    </ul>
<% end %>

app/views/static_pages/_articles.html.erb
<% require 'embedly' %>
<% require 'mechanize' %>
<% @articles.each do |article| %>
    <ul class="thumbnails">
      <li class="span12">
        <% embedly_api = Embedly::API.new :key => '8a3c9238c6504b64816fcfc54fc2fa89', :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; asampat3090@gmail.com)' %>
        <%   obj = embedly_api.oembed(url: article.url, maxwidth: 450, wmode: 'transparent', method: 'after')  %>

        <a href=<%=article.url%> class="thumbnail" target="_blank">
            <h2><%= obj[0].title%></h2>
			<% if article.created_at != nil %>
            	<h4 class="text-center"><%=(article.created_at + Time.zone_offset('PST')).strftime("%m/%d/%Y at %I:%M%p")%></h4>
			<%end%>
			<% if obj[0].provider_url != nil%>
				<% img_url = obj[0].provider_url + "/favicon.ico" %>
				<% agent = Mechanize.new %>
            	<%# res = agent.get(URI.parse(img_url)) %>
            	<% res = Net::HTTP.get_response(URI.parse(img_url)) %>
            	<% img_url = '' unless res.code.to_i >= 200 && res.code.to_i < 400 #good codes will be betweem 200 - 399 %>
            	<% if img_url != '' %>
                	<h4 class="text-center"> <%= image_tag img_url, alt: "provider favicon", size: "64x64" %></h4>
            	<% end %>
            	<% if obj[0].thumbnail_url != nil %>
                	<%= image_tag obj[0].thumbnail_url, alt: obj[0].title %>
            	<% end %>
			<% end %>
            <br/>
            <p><%= obj[0].description %> </p>
        </a>
      </li>
    </ul>
<% end %>

app/views/static_pages/_blog_post.html.erb
<% @blog_posts.each do |entry| %>
<div>
  <a href=<%=entry.url%>><h3 class = "blog"> <%= entry.title %> </h3></a>
  <h4><%=entry.published.strftime("%m/%d/%Y at %I:%M%p")%></h4>
  <br />
  <!-- Twitter Share Button -->
  <a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  <!-- end Twitter Share Button -->
  <p>
    <%= simple_format entry.content.html_safe %>
  </p>
  <br />
  <% entry.categories.each do |category| %>
  <%= category %>,
  <% end %>
</div>
<% end %>

app/views/static_pages/_books_read.html.erb
<% require 'embedly' %>
<% require 'mechanize' %>
<% @books_read.each do |book_read| %>
    <ul class="thumbnails">
      <li class="span12">
        

        <a href=<%=book_read.link%> class="thumbnail" target="_blank">
            <h2><%= book_read.title%></h2>
            <h4 class="text-center">Average Rating: <%= book_read.average_rating%></h4>
			<!--
            <% if book_read.created_at != nil %>
            	<h4 class="text-center"><%=(book_read.created_at + Time.zone_offset('PST')).strftime("%m/%d/%Y at %I:%M%p")%></h4>
			<%end%>
            -->
			<% if book_read.image_url != nil %>
            	<%= image_tag book_read.image_url, alt: book_read.title %>
			<% end %>
            <br/>
            <p><%= book_read.description %> </p>
        </a>
      </li>
    </ul>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Me') %>
<h1>About Me</h1>
<div class="thumbnail">

  <div class="row-fluid">
    <div class="span3 offset1">
      <%= image_tag("about/berkeley_seal.gif", alt: "UC Berkeley Seal", size: "150x150") %>
    </div>

    <div class="span4">
      <%= image_tag("about/about_pic.png", alt: "rss feed") %>
    </div>

    <div class="span3 offset1">
      <%= image_tag("about/stanford_seal.gif", alt: "Stanford Seal", size: "150x150") %>
    </div>
  </div>


  <br />

  <p style="text-align:center">2012 Graduation Reception in Heart Mining Memorial Building at UC Berkeley.</p>
</div>
<p>
  I'm a technology enthusiast who previously specialized in semiconductor technology and now specializes in computer software.
  I've made this page to present my various projects, and aggregate my social networks. Please check out my <a href="http://facebook.com/anand.sampat">Facebook</a>,
  <a href="http://twitter.com/AnandSampat">Twitter</a> (please follow if they're interesting), and <a href="http://www.linkedin.com/in/anandsampat">LinkedIn</a> (feel free to connect).
  I also have my profiles up on <a href="http://www.primsly.com/users/709742213">Primsly</a>, a website aimed at turning the job hunt process on its head - the companies make a possible offer before the interview process is initiated.
  Another great site where I have my profile hosted is <a href="http://collegefeed.com/profile/asampat3090">collegefeed</a>, a portal to help students kickstart their careers.
  Also check out my <a href="http://anandsampat.com/blog">blog</a> where I'll share my thoughts, my insights, and interesting articles on everything from consumer electronics, Bollywood, books, and life.
  I invite my readers to share their thoughts and comments - the more the merrier.
</p>

app/views/static_pages/blog.html.erb
<% provide(:title, 'Blog') %>
<%= load_blog_feed%>
<h1>Blog - <%= @feed_title %></h1>

<div class="row-fluid">
  <div class="span8">
    <%= render partial: "blog_post" %>
  </div>
  <div class="span4">
    <!--Some history of blog posts   -->
    <br />
    <a class="twitter-timeline" width="1000" href="https://twitter.com/AnandSampat" data-widget-id="299970850923364352">Tweets by @AnandSampat</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <br />
    <!-- Facebook widget   -->
  </div>
</div>

app/views/static_pages/book_reading.html.erb
<% provide(:title, "Books") %>
<% load_book_feed %>

<h1>Recently Read Books</h1>
<div id="books_read"><%= render partial: 'books_read' %></div>
<% if params[:page].to_i==0 %>
<% params[:page]=1 %>
<% end %>
<%= link_to 'Load More', book_reading_path(page: (params[:page].to_i || 1)+1, per_page: params[:per_page] || 5), class: 'book_hook', remote: true %>

app/views/static_pages/book_reading.js.erb
<% if @books_read.all.count>0 -%>
$('#books_read').append('<%= escape_javascript(render(partial: 'books_read')) %>');
$('a.book_hook').attr('href', '<%= book_reading_path(page: (params[:page].to_i || 1)+1, per_page: params[:per_page] || 5) %>').show();
<% else -%>
$('a.book_hook').hide();
<% end -%>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<br/>
<br/>
<div class="center hero-unit" >
  <h1>
    <%= image_tag("homepage/berkeley_logo.png", alt: "UC Berkeley Logo - Cal", size: "150x150") %>
    Anand Sampat
    <%= image_tag("homepage/stanford_logo.png", alt: "Stanford Logo - S", size: "100x100") %>
  </h1>

  <h2>
    I dream about efficiency.
  </h2>

  <!-- INSERT CODE FOR GITHUB, LINKEDIN, TWITTER, FB HERE -->
  <div class="pagination-centered">
    <%= link_to image_tag("homepage/linkedin.png", alt: "linkedin link", size: "100x100"), "http://www.linkedin.com/in/anandsampat/"%>
    <%= link_to image_tag("homepage/twitter.png", alt: "twitter link", size: "100x100"), "http://www.twitter.com/AnandSampat" %>
    <%= link_to image_tag("homepage/quora.png", alt: "quora link", size: "100x100"), "http://www.quora.com/Anand-Sampat" %>
    <%= link_to image_tag("homepage/github.png", alt: "github link", size: "100x100"), "http://www.github.com/asampat3090" %>
  </div>
  
  <br />


  <%= link_to "My Projects", projects_path, class: "btn btn-large btn-primary" %>
  <br />
  <br />
  <iframe src="http://www.codility.com//cert/badge/certEXMNT8-HANGBCCR466FUTHW/" width="125" height="75" >
    <a href="http://www.codility.com//cert/view/certEXMNT8-HANGBCCR466FUTHW/">Codility badge</a>
  </iframe>
  <iframe src="https://codility.com//cert/badge/cert2J5ME4-4U6ENKX3HU43R4YM/" width="125" height="75" >
    <a href="https://codility.com//cert/view/cert2J5ME4-4U6ENKX3HU43R4YM/">Codility badge</a>
  </iframe>
</div>

<div id="myCarousel" class="carousel slide">

  <!-- Carousel items -->
  <div class="carousel-inner">

    <div class="active item">
      <%= image_tag("homepage_carousel/UC_Berkeley_sf_view.jpeg", alt: "Berkeley") %>
      <div class="carousel-caption">
        <p>Beautiful view of the Campanile, Berkeley, and SF.</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag("homepage_carousel/sather_gate.jpeg", alt: "Berkeley") %>
      <div class="carousel-caption">
        <p>The hustle and bustle of Sproul Plaza</p>
      </div>
    </div>
    <div class="item">
      <%= image_tag("homepage_carousel/Stanford_Memorial_Church.png", alt:  "Stanford") %>
      <div class="carousel-caption">
        <p>The other school across the Bay - beautiful in its own way.</p>
      </div>
    </div>

  </div>
  <!-- Carousel nav -->
  <a id="cl" class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a id="cr" class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>


<script>
    $('#myCarousel').carousel({
        interval: 5000
    });
</script>

app/views/static_pages/projects.html.erb
<% provide(:title, 'Projects') %>
<h1 xmlns="http://www.w3.org/1999/html">Projects</h1>
<h2>Hardware</h2>
<ul class="thumbnails">
  <li class="span6">
    <a href="https://docs.google.com/file/d/0B_j1yTxBbZYAaFg4OERfTWxwR0U/edit" class="thumbnail">
      <%= image_tag("projects/Berkeley_MS_Thesis.png", alt: "E-k diagram for graphene", size: "300x300") %>
      <h2>
        Berkeley MS Thesis - Molecular Beam Epitaxy of Graphene on Gold Foils
      </h2>
      <p style="text-align:left">My thesis on the growth of graphene films on gold foils and a correlation of growth parameters to
        mechanical and electrical characteristics.
      </p>
    <a>
  </li>
  <li class="span6">

    <a href="https://docs.google.com/file/d/0B_j1yTxBbZYALXVMN210aU9mODQ/" class="thumbnail">
      <%= image_tag("projects/pentacene_transistor.png", alt: "cross-section of pentacene bottom gate transistor", size: "235x235") %>
      <h2>
        An Analytical Model for Switching Speed in an all Ink-Jet Printed Self-Aligned Pentacene Inverter
      </h2>
      <p style="text-align:left">
        My research project creating an analytical model for the switching speed of an inverter built using pentacene bottom gate organic transistors.
      </p>
    <a>

  </li>
</ul>

<h2>Software</h2>

<ul class="thumbnails">
  <li class="span6">
    <a href="https://github.com/asampat3090/one_pager" class="thumbnail">
      <%= image_tag("projects/one_pager_icon.png", alt: "one pager summary list icon", size: "300x300") %>
      <h2>
        Basic Django Web App (not deployed) - Create a One-Pager
      </h2>
      <p style="text-align:left">Small web app to create a one-pager summarizing the tasks and meetings completed over the past week. Covers only basic functionality but this is my first Django app - still needs a lot of polishing.
      </p>
      <a>
  </li>
  <li class="span6">
    <a href="https://github.com/asampat3090/kayak_weather_chrome_ext" class="thumbnail">
      <br/>
      <%= image_tag("projects/sun.png", alt: "cartoon sun", size: "300x300") %>
      <h2>
        Warmest Destinations Chrome Extension
      </h2>
      <p style="text-align:left">
        Small Chrome extension to poll Geonames and WeatherBug APIs to find the warmest destinations within a 30 km radius of the destination searched by the user.
      </p>
      <a>
  </li>

  <li class="span6">
    <a href="https://github.com/asampat3090/xkcd_screensaver_for_kindle" class="thumbnail">
      <%= image_tag("projects/kindle-xkcd.jpeg", alt: "xkcd on kindle screensaver icon", size: "300x300") %>
      <h2>
        xkcd for Kindle Keyboard Screensavers
      </h2>
      <p style="text-align:left">
        Script to scrape xkcd for most recent comments and saves images in folder for transfer to kindle. Will turn this into a web app/add-on soon. Also, will add documentation to add it to kindle as screensaver.
      </p>
    <a>
  </li>


</ul>

<p>

</p>

app/views/static_pages/reading.html.erb
<% provide(:title, 'Articles') %>
<% load_reading_feed %>

<h1>My Current Reading</h1>
<div id="articles"><%= render partial: 'articles' %></div>
<% if params[:page].to_i==0 %>
<% params[:page]=1 %>
<% end %>
<%= link_to 'Load More', reading_path(page: (params[:page].to_i || 1)+1, per_page: params[:per_page] || 5), class: 'hook', remote: true %>


<!--
<div id="articles">
	<%#= render partial: "articles" %>
</div>
<h4 class="text-center"><%#= will_paginate @articles %></h4>
-->

app/views/static_pages/reading.js.erb
<% if @articles.all.count>0 -%>
$('#articles').append('<%= escape_javascript(render(partial: 'articles')) %>');
$('a.hook').attr('href', '<%= reading_path(page: (params[:page].to_i || 1)+1, per_page: params[:per_page] || 5) %>').show();
<% else -%>
$('a.hook').hide();
<% end -%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>